version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bandage-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: bandage-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    restart: always

  bandage-band-manager:
    image: 595028889928.dkr.ecr.ap-northeast-2.amazonaws.com/bandage-band-manager:dev-latest
    container_name: bandage-band-manager
    expose:
      - "${BAND_MANAGER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

#  bandage-music-metadata:
#    image: 595028889928.dkr.ecr.ap-northeast-2.amazonaws.com/bandage-music-metadata:latest
#    container_name: bandage-music-metadata
#    ports:
#      - "8081:8081"
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - redis
#    restart: always