spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:bandage_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  access-token-expr: 3600
  refresh-token-expr: 25200
  secret: "OXCdljnxxIeLMbX/dnQIWyVSuVAdkGc6p6FYaChtCb6Zzg//p1tdUwekTL/CB7QPNf47GjGhhRvXYe2bs3UWTg=="

oauth:
  google:
    token-info-uri: https://oauth2.googleapis.com/tokeninfo
    client-id: test-client-id
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: test-kakao-client-id
    client-secret: test-kakao-client-secret

aws:
  credentials:
    access-key: test-access-key
    secret-key: test-secret-key
  region:
    static: ap-northeast-2
  s3:
    bucket: test-bucket
  cloudfront:
    domain: test.cloudfront.net

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE