jwt:
  access-token-expr: 3600
  refresh-token-expr: 25200
  secret: ${JWT_TOKEN_SECRET}

oauth:
  kakao:
    user-info-uri: ${KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}
  google:
    token-info-uri: ${GOOGLE_TOKEN_INFO_URI:https://oauth2.googleapis.com/tokeninfo}
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}