-- =====================================================================
-- 001-init-schema.sql
--
-- 현재 운영 중인 PostgreSQL 스키마(public)를 그대로 재현하는 초기
-- 스키마 정의. pg_dump --schema-only 결과(2026-05-05 기준)에서 세션
-- 설정/소유자 메타데이터만 제거하고 DDL 본문만 유지.
--
-- 주의:
--   - 신규/clean DB 부팅 시 Liquibase 가 본 changeset 을 실행해 전체
--     스키마를 생성한다.
--   - 이미 동일 스키마가 존재하는 환경(로컬 dev / 운영)에 처음 도입할
--     때는 `liquibase changelog-sync` 로 changeset 을 실행 없이
--     이력만 기록해야 중복 CREATE 오류가 발생하지 않는다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------

CREATE TABLE public.p_band (
    member_cnt integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    band_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    profile_img character varying(255),
    description oid NOT NULL
);

CREATE TABLE public.p_band_application (
    status smallint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    processed_by bigint,
    band_id uuid NOT NULL,
    id uuid NOT NULL,
    CONSTRAINT p_band_application_status_check CHECK (((status >= 0) AND (status <= 4)))
);

CREATE TABLE public.p_band_member (
    role smallint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    band_id uuid NOT NULL,
    band_member_id uuid NOT NULL,
    CONSTRAINT p_band_member_role_check CHECK (((role >= 0) AND (role <= 2)))
);

CREATE TABLE public.p_member (
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    last_modified_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    contact character varying(255),
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    profile_img character varying(255)
);

CREATE TABLE public.p_member_auth (
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    last_modified_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255),
    role character varying(255) NOT NULL,
    CONSTRAINT p_member_auth_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'KAKAO'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT p_member_auth_role_check CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'ADMIN'::character varying, 'DEVELOPER'::character varying])::text[])))
);

ALTER TABLE public.p_member ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.p_member_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.p_member_schedule (
    completed boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    user_id bigint NOT NULL,
    meeting_id uuid NOT NULL,
    note character varying(500)
);

CREATE TABLE public.p_member_schedule_available_dates (
    date_value date NOT NULL,
    user_id bigint NOT NULL,
    meeting_id uuid NOT NULL
);

CREATE TABLE public.p_member_schedule_blocks (
    date_key date NOT NULL,
    user_id bigint NOT NULL,
    block_hex character varying(12) NOT NULL,
    meeting_id uuid NOT NULL
);

CREATE TABLE public.p_member_schedule_unavailable_dates (
    date_value date NOT NULL,
    user_id bigint NOT NULL,
    meeting_id uuid NOT NULL
);

CREATE TABLE public.p_performance (
    duration_minutes integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    start_at timestamp(6) without time zone NOT NULL,
    performance_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    venue character varying(255)
);

CREATE TABLE public.p_performance_band (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    band_id uuid NOT NULL,
    performance_band_id uuid NOT NULL,
    performance_id uuid NOT NULL
);

CREATE TABLE public.p_performance_manager (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    performance_id uuid NOT NULL,
    performance_manager_id uuid NOT NULL
);

CREATE TABLE public.p_performance_practice (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    performance_id uuid NOT NULL,
    performance_practice_id uuid NOT NULL,
    practice_id uuid NOT NULL
);

CREATE TABLE public.p_practice (
    duration_minutes integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    start_at timestamp(6) without time zone NOT NULL,
    practice_id uuid NOT NULL,
    song_id uuid,
    title character varying(255) NOT NULL,
    venue character varying(255)
);

CREATE TABLE public.p_practice_participant (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint,
    practice_id uuid,
    practice_participant_id uuid NOT NULL
);

CREATE TABLE public.p_practice_session (
    session_type smallint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    participant_id uuid,
    practice_id uuid,
    practice_session_id uuid NOT NULL,
    label character varying(255),
    CONSTRAINT p_practice_session_session_type_check CHECK (((session_type >= 0) AND (session_type <= 7)))
);

CREATE TABLE public.p_practice_song (
    duration integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    practice_song_id uuid NOT NULL,
    album character varying(255) NOT NULL,
    artist character varying(255) NOT NULL,
    ref_link character varying(255),
    title character varying(255) NOT NULL
);

CREATE TABLE public.p_schedule_block (
    block_date date NOT NULL,
    duration_slots integer NOT NULL,
    palette_index integer,
    pinned boolean NOT NULL,
    start_slot integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    schedule_block_id uuid NOT NULL,
    schedule_board_id uuid NOT NULL,
    song_id uuid NOT NULL,
    note character varying(200),
    song_title_override character varying(255)
);

CREATE TABLE public.p_schedule_board (
    confirmed boolean NOT NULL,
    exclude_late_night boolean NOT NULL,
    max_consecutive_minutes integer NOT NULL,
    palette_seed integer,
    working_hours_end integer NOT NULL,
    working_hours_start integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    version bigint NOT NULL,
    meeting_id uuid NOT NULL,
    schedule_board_id uuid NOT NULL,
    name character varying(50) NOT NULL
);

CREATE TABLE public.p_setlist_item (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    proposer_id bigint NOT NULL,
    meeting_id uuid NOT NULL,
    practice_song_id uuid,
    setlist_item_id uuid NOT NULL,
    note character varying(1000),
    album character varying(255),
    artist character varying(255) NOT NULL,
    duration character varying(255),
    title character varying(255) NOT NULL
);

CREATE TABLE public.p_setlist_item_applicant (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    applicant_id uuid NOT NULL,
    setlist_item_id uuid NOT NULL,
    session_id character varying(255) NOT NULL
);

CREATE TABLE public.p_setlist_item_chat_message (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    message_id uuid NOT NULL,
    setlist_item_id uuid NOT NULL,
    message character varying(500) NOT NULL
);

CREATE TABLE public.p_setlist_item_confirmation (
    confirmed_by bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    confirmation_id uuid NOT NULL,
    setlist_item_id uuid NOT NULL,
    session_id character varying(255) NOT NULL
);

CREATE TABLE public.p_setlist_item_session (
    session_custom boolean NOT NULL,
    session_need integer NOT NULL,
    setlist_item_id uuid NOT NULL,
    label character varying(255) NOT NULL,
    session_id character varying(255) NOT NULL,
    session_short character varying(255) NOT NULL
);

CREATE TABLE public.p_setlist_meeting (
    practice_window_from date NOT NULL,
    practice_window_to date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    locked_at timestamp(6) without time zone,
    manager_id bigint NOT NULL,
    band_id uuid NOT NULL,
    meeting_id uuid NOT NULL,
    performance_id uuid,
    purpose character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT p_setlist_meeting_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['PERFORMANCE'::character varying, 'GENERAL'::character varying])::text[])))
);

CREATE TABLE public.p_setlist_meeting_member (
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    last_modified_at timestamp(6) without time zone NOT NULL,
    last_modified_by bigint,
    member_id bigint NOT NULL,
    meeting_id uuid NOT NULL,
    meeting_member_id uuid NOT NULL
);

-- ---------------------------------------------------------------------
-- Primary keys & unique constraints
-- ---------------------------------------------------------------------

ALTER TABLE ONLY public.p_band_application
    ADD CONSTRAINT p_band_application_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.p_band_member
    ADD CONSTRAINT p_band_member_pkey PRIMARY KEY (band_member_id);

ALTER TABLE ONLY public.p_band
    ADD CONSTRAINT p_band_name_key UNIQUE (name);

ALTER TABLE ONLY public.p_band
    ADD CONSTRAINT p_band_pkey PRIMARY KEY (band_id);

ALTER TABLE ONLY public.p_member_auth
    ADD CONSTRAINT p_member_auth_email_key UNIQUE (email);

ALTER TABLE ONLY public.p_member_auth
    ADD CONSTRAINT p_member_auth_pkey PRIMARY KEY (member_id);

ALTER TABLE ONLY public.p_member
    ADD CONSTRAINT p_member_email_key UNIQUE (email);

ALTER TABLE ONLY public.p_member
    ADD CONSTRAINT p_member_pkey PRIMARY KEY (member_id);

ALTER TABLE ONLY public.p_member_schedule_available_dates
    ADD CONSTRAINT p_member_schedule_available_dates_pkey PRIMARY KEY (date_value, user_id, meeting_id);

ALTER TABLE ONLY public.p_member_schedule_blocks
    ADD CONSTRAINT p_member_schedule_blocks_pkey PRIMARY KEY (date_key, user_id, meeting_id);

ALTER TABLE ONLY public.p_member_schedule
    ADD CONSTRAINT p_member_schedule_pkey PRIMARY KEY (user_id, meeting_id);

ALTER TABLE ONLY public.p_member_schedule_unavailable_dates
    ADD CONSTRAINT p_member_schedule_unavailable_dates_pkey PRIMARY KEY (date_value, user_id, meeting_id);

ALTER TABLE ONLY public.p_performance_band
    ADD CONSTRAINT p_performance_band_pkey PRIMARY KEY (performance_band_id);

ALTER TABLE ONLY public.p_performance_manager
    ADD CONSTRAINT p_performance_manager_pkey PRIMARY KEY (performance_manager_id);

ALTER TABLE ONLY public.p_performance
    ADD CONSTRAINT p_performance_pkey PRIMARY KEY (performance_id);

ALTER TABLE ONLY public.p_performance_practice
    ADD CONSTRAINT p_performance_practice_pkey PRIMARY KEY (performance_practice_id);

ALTER TABLE ONLY public.p_practice_participant
    ADD CONSTRAINT p_practice_participant_pkey PRIMARY KEY (practice_participant_id);

ALTER TABLE ONLY public.p_practice
    ADD CONSTRAINT p_practice_pkey PRIMARY KEY (practice_id);

ALTER TABLE ONLY public.p_practice_session
    ADD CONSTRAINT p_practice_session_participant_id_key UNIQUE (participant_id);

ALTER TABLE ONLY public.p_practice_session
    ADD CONSTRAINT p_practice_session_pkey PRIMARY KEY (practice_session_id);

ALTER TABLE ONLY public.p_practice
    ADD CONSTRAINT p_practice_song_id_key UNIQUE (song_id);

ALTER TABLE ONLY public.p_practice_song
    ADD CONSTRAINT p_practice_song_pkey PRIMARY KEY (practice_song_id);

ALTER TABLE ONLY public.p_schedule_block
    ADD CONSTRAINT p_schedule_block_pkey PRIMARY KEY (schedule_block_id);

ALTER TABLE ONLY public.p_schedule_board
    ADD CONSTRAINT p_schedule_board_pkey PRIMARY KEY (schedule_board_id);

ALTER TABLE ONLY public.p_setlist_item_applicant
    ADD CONSTRAINT p_setlist_item_applicant_pkey PRIMARY KEY (applicant_id);

ALTER TABLE ONLY public.p_setlist_item_chat_message
    ADD CONSTRAINT p_setlist_item_chat_message_pkey PRIMARY KEY (message_id);

ALTER TABLE ONLY public.p_setlist_item_confirmation
    ADD CONSTRAINT p_setlist_item_confirmation_pkey PRIMARY KEY (confirmation_id);

ALTER TABLE ONLY public.p_setlist_item
    ADD CONSTRAINT p_setlist_item_pkey PRIMARY KEY (setlist_item_id);

ALTER TABLE ONLY public.p_setlist_meeting_member
    ADD CONSTRAINT p_setlist_meeting_member_pkey PRIMARY KEY (meeting_member_id);

ALTER TABLE ONLY public.p_setlist_meeting
    ADD CONSTRAINT p_setlist_meeting_pkey PRIMARY KEY (meeting_id);

ALTER TABLE ONLY public.p_setlist_item_applicant
    ADD CONSTRAINT uk_setlist_item_applicant UNIQUE (setlist_item_id, session_id, member_id);

ALTER TABLE ONLY public.p_setlist_item_confirmation
    ADD CONSTRAINT uk_setlist_item_confirmation UNIQUE (setlist_item_id, session_id, member_id);

ALTER TABLE ONLY public.p_setlist_meeting_member
    ADD CONSTRAINT uk_setlist_meeting_member UNIQUE (meeting_id, member_id);

-- ---------------------------------------------------------------------
-- Foreign keys (Hibernate 자동 생성 이름 그대로 보존)
-- ---------------------------------------------------------------------

ALTER TABLE ONLY public.p_setlist_item_confirmation
    ADD CONSTRAINT fk1jnd47c15svyvj5etnshc54w4 FOREIGN KEY (setlist_item_id) REFERENCES public.p_setlist_item(setlist_item_id);

ALTER TABLE ONLY public.p_setlist_item_session
    ADD CONSTRAINT fk21p0ohliw227nywlmrx9mx90n FOREIGN KEY (setlist_item_id) REFERENCES public.p_setlist_item(setlist_item_id);

ALTER TABLE ONLY public.p_practice_session
    ADD CONSTRAINT fk4lhltgltjbyvy0i7dgem2eaxb FOREIGN KEY (practice_id) REFERENCES public.p_practice(practice_id);

ALTER TABLE ONLY public.p_setlist_meeting_member
    ADD CONSTRAINT fk7lh5uba1i30yorttxhqow5897 FOREIGN KEY (meeting_id) REFERENCES public.p_setlist_meeting(meeting_id);

ALTER TABLE ONLY public.p_performance_band
    ADD CONSTRAINT fk8dxivicbb7w1nwmpp903i5dnn FOREIGN KEY (performance_id) REFERENCES public.p_performance(performance_id);

ALTER TABLE ONLY public.p_practice_session
    ADD CONSTRAINT fk8e14chapbmf58guwyko3dy58p FOREIGN KEY (participant_id) REFERENCES public.p_practice_participant(practice_participant_id);

ALTER TABLE ONLY public.p_practice_participant
    ADD CONSTRAINT fk8jbcy18m52b8gb459hdk3rwyb FOREIGN KEY (practice_id) REFERENCES public.p_practice(practice_id);

ALTER TABLE ONLY public.p_schedule_block
    ADD CONSTRAINT fka090ge64j62laepg6nrhv1hn9 FOREIGN KEY (schedule_board_id) REFERENCES public.p_schedule_board(schedule_board_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.p_performance_practice
    ADD CONSTRAINT fke1ph10s8nyfkoq6whfhj8bfbm FOREIGN KEY (performance_id) REFERENCES public.p_performance(performance_id);

ALTER TABLE ONLY public.p_setlist_item_chat_message
    ADD CONSTRAINT fkeygfgelvoh0by7xjecs5vi8oo FOREIGN KEY (setlist_item_id) REFERENCES public.p_setlist_item(setlist_item_id);

ALTER TABLE ONLY public.p_member_schedule_available_dates
    ADD CONSTRAINT fkf02hp786er8lmusqjx8j8ko6 FOREIGN KEY (user_id, meeting_id) REFERENCES public.p_member_schedule(user_id, meeting_id);

ALTER TABLE ONLY public.p_setlist_item
    ADD CONSTRAINT fki8gfhyor161vlcwfldxrql7ee FOREIGN KEY (meeting_id) REFERENCES public.p_setlist_meeting(meeting_id);

ALTER TABLE ONLY public.p_member_schedule_blocks
    ADD CONSTRAINT fkkht7cxnhxnciuql5jhak99b1l FOREIGN KEY (user_id, meeting_id) REFERENCES public.p_member_schedule(user_id, meeting_id);

ALTER TABLE ONLY public.p_performance_practice
    ADD CONSTRAINT fkn9bnx9cfeog2yuosmbabcxvc7 FOREIGN KEY (practice_id) REFERENCES public.p_practice(practice_id);

ALTER TABLE ONLY public.p_setlist_item_applicant
    ADD CONSTRAINT fko1xsrkig3tkkowytdfo1p85ao FOREIGN KEY (setlist_item_id) REFERENCES public.p_setlist_item(setlist_item_id);

ALTER TABLE ONLY public.p_practice
    ADD CONSTRAINT fkoierh8dymh6ktaya3f2hxxk90 FOREIGN KEY (song_id) REFERENCES public.p_practice_song(practice_song_id);

ALTER TABLE ONLY public.p_member_schedule_unavailable_dates
    ADD CONSTRAINT fkpe6bmed5e71gq5br2hsu4qmj4 FOREIGN KEY (user_id, meeting_id) REFERENCES public.p_member_schedule(user_id, meeting_id);

ALTER TABLE ONLY public.p_performance_manager
    ADD CONSTRAINT fkpidrhwf6s6o75sq8s557pc3k0 FOREIGN KEY (performance_id) REFERENCES public.p_performance(performance_id);

ALTER TABLE ONLY public.p_band_member
    ADD CONSTRAINT fkppxvlq8t0bg6ci6ru4jxlx47o FOREIGN KEY (band_id) REFERENCES public.p_band(band_id);

ALTER TABLE ONLY public.p_band_application
    ADD CONSTRAINT fkt77fejmtlywqv33qqglo73khy FOREIGN KEY (band_id) REFERENCES public.p_band(band_id);
